version: '3.8'
services:
  database:
    container_name: "ebjdbdev"
    restart: unless-stopped
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "ebj"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ebjdbdev:/var/lib/postgresql/data
volumes:
  ebjdbdev: